import { useState, useEffect, useCallback } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { toast } from 'sonner';
import { Database } from '@/integrations/supabase/types';

type TicketStatus = Database['public']['Enums']['ticket_status'];
type TicketPriority = Database['public']['Enums']['ticket_priority'];

export interface SupportTicket {
  id: string;
  ticket_number: string;
  client_id: string | null;
  user_id: string;
  subject: string;
  description: string;
  status: TicketStatus;
  priority: TicketPriority;
  assigned_to: string | null;
  created_at: string;
  updated_at: string;
  resolved_at: string | null;
  user_email?: string;
  client_name?: string;
}

export interface SupportMessage {
  id: string;
  ticket_id: string | null;
  sender_id: string;
  message: string;
  is_admin: boolean;
  is_read: boolean;
  created_at: string;
  sender_email?: string;
}

export function useSupportTickets() {
  const { user, isAdmin, isClient } = useAuth();
  const [tickets, setTickets] = useState<SupportTicket[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  const fetchTickets = useCallback(async () => {
    if (!user) return;

    setIsLoading(true);
    try {
      let query = supabase
        .from('support_tickets')
        .select('*')
        .order('created_at', { ascending: false });

      if (isAdmin) {
        // AMEX admin: exclude tickets from portal users (end-clients).
        // End-client tickets are handled in the Client Inbox tab.
        const { data: portalUserIds } = await supabase
          .from('portal_users')
          .select('user_id');
        
        const excludedIds = (portalUserIds || []).map((p: { user_id: string }) => p.user_id);
        
        if (excludedIds.length > 0) {
          query = query.not('user_id', 'in', `(${excludedIds.join(',')})`);
        }
      } else {
        // Client users: only THEIR OWN tickets to AMEX Outsourcing.
        // End-client tickets are shown separately in Client Inbox tab.
        query = query.eq('user_id', user.id);
      }

      const { data, error } = await query;

      if (error) throw error;

      // Batch fetch client names (no profile lookups — RLS blocks cross-user reads)
      const clientIds = [...new Set((data || []).map(t => t.client_id).filter(Boolean))];
      let clientMap: Record<string, string> = {};
      if (clientIds.length > 0) {
        const { data: clientsData } = await supabase
          .from('clients')
          .select('id, company_name')
          .in('id', clientIds as string[]);
        clientMap = Object.fromEntries((clientsData || []).map(c => [c.id, c.company_name]));
      }

      setTickets((data || []).map(t => ({
        ...t,
        client_name: t.client_id ? clientMap[t.client_id] : undefined,
      })));
    } catch (error) {
      console.error('Error fetching tickets:', error);
      toast.error('Failed to load tickets');
    } finally {
      setIsLoading(false);
    }
  }, [user, isAdmin, isClient]);

  useEffect(() => {
    fetchTickets();
  }, [fetchTickets]);

  const createTicket = async (subject: string, description: string, priority: TicketPriority = 'medium') => {
    if (!user) return null;

    try {
      // Get client_id if user is a client
      const { data: clientUser } = await supabase
        .from('client_users')
        .select('client_id')
        .eq('user_id', user.id)
        .single();

      const { data, error } = await supabase
        .from('support_tickets')
        .insert({
          user_id: user.id,
          client_id: clientUser?.client_id || null,
          subject,
          description,
          priority,
          ticket_number: '', // Will be auto-generated by trigger
        })
        .select()
        .single();

      if (error) throw error;

      toast.success('Ticket created successfully');
      fetchTickets();
      return data;
    } catch (error) {
      console.error('Error creating ticket:', error);
      toast.error('Failed to create ticket');
      return null;
    }
  };

  const updateTicketStatus = async (ticketId: string, status: TicketStatus) => {
    try {
      const updateData: { status: TicketStatus; resolved_at?: string | null } = { status };
      if (status === 'resolved' || status === 'closed') {
        updateData.resolved_at = new Date().toISOString();
      } else {
        updateData.resolved_at = null;
      }

      const { error } = await supabase
        .from('support_tickets')
        .update(updateData)
        .eq('id', ticketId);

      if (error) throw error;

      toast.success('Ticket status updated');
      fetchTickets();
    } catch (error) {
      console.error('Error updating ticket:', error);
      toast.error('Failed to update ticket');
    }
  };

  const deleteTicket = async (ticketId: string): Promise<boolean> => {
    try {
      const { error } = await supabase
        .from('support_tickets')
        .delete()
        .eq('id', ticketId);
      if (error) throw error;
      toast.success('Ticket deleted');
      fetchTickets();
      return true;
    } catch (error) {
      console.error('Error deleting ticket:', error);
      toast.error('Failed to delete ticket');
      return false;
    }
  };

  const getMessages = async (ticketId: string): Promise<SupportMessage[]> => {
    try {
      const { data, error } = await supabase
        .from('support_messages')
        .select('*')
        .eq('ticket_id', ticketId)
        .order('created_at', { ascending: true });
      if (error) throw error;
      return (data || []) as SupportMessage[];
    } catch (error) {
      console.error('Error fetching messages:', error);
      return [];
    }
  };

  const sendMessage = async (ticketId: string, message: string) => {
    if (!user) return null;

    try {
      const { data, error } = await supabase
        .from('support_messages')
        .insert({
          ticket_id: ticketId,
          sender_id: user.id,
          message,
          is_admin: isAdmin,
        })
        .select()
        .single();

      if (error) throw error;
      return data;
    } catch (error) {
      console.error('Error sending message:', error);
      toast.error('Failed to send message');
      return null;
    }
  };

  const markMessagesAsRead = async (ticketId: string) => {
    if (!user) return;

    try {
      await supabase
        .from('support_messages')
        .update({ is_read: true })
        .eq('ticket_id', ticketId)
        .neq('sender_id', user.id);
    } catch (error) {
      console.error('Error marking messages as read:', error);
    }
  };

  const subscribeToMessages = (ticketId: string, callback: (message: SupportMessage) => void) => {
    const channel = supabase
      .channel(`ticket-${ticketId}`)
      .on(
        'postgres_changes',
        {
          event: 'INSERT',
          schema: 'public',
          table: 'support_messages',
          filter: `ticket_id=eq.${ticketId}`,
        },
        (payload) => {
          callback(payload.new as SupportMessage);
        }
      )
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  };

  return {
    tickets,
    isLoading,
    createTicket,
    updateTicketStatus,
    deleteTicket,
    getMessages,
    sendMessage,
    markMessagesAsRead,
    subscribeToMessages,
    refreshTickets: fetchTickets,
  };
}
